version: '3.5'

services:
  nginx:
    image: nginx
    restart: on-failure
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - front
      - gateway
      - students
      - faculties
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  front:
    build: front
    restart: on-failure
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - gateway
      - students
      - faculties

  gateway:
    build: gateway
    restart: on-failure
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      - faculties_url=http://faculties:8081/api
      - students_url=http://students:8085/api

  students:
    build: students
    restart: on-failure
    ports:
      - "0.0.0.0:8085:8085"

  faculties:
    build: faculties
    restart: on-failure
    ports:
      - "0.0.0.0:8081:8081"
    environment:
      - students_url=http://students:8085/api/

networks:
  default:
