version: '3.5'

services:
  nginx:
    image: nginx
    restart: on-failure
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - front
      - gateway
      - students
      - faculties
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  front:
    build: front
    restart: on-failure
    depends_on:
      - gateway
      - students
      - faculties

  gateway:
    build: gateway
    restart: on-failure
    environment:
      - FACULTIES_API_URL=http://faculties
      - STUDENTS_API_URL=http://students
      - GATEWAY_API_URL=gateway

  students:
    build: students
    restart: on-failure

  faculties:
    build: faculties
    restart: on-failure
    environment:
      - STUDENTS_API_URL=http://students/api

networks:
  default:
