version: '3.5'

services:
  nginx:
    image: nginx
    restart: on-failure
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - front
      - gateway
      - students
      - faculties
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  front:
    build: front
    restart: on-failure
    depends_on:
      - gateway
      - students
      - faculties

  gateway:
    build: gateway
    restart: on-failure
    environment:
      - faculties_url=http://faculties
      - students_url=http://students
      - gateway_url=gateway

  students:
    build: students
    restart: on-failure

  faculties:
    build: faculties
    restart: on-failure
    environment:
      - students_url=http://students/api

networks:
  default:
